build: false

image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3-x64
environment:
  matrix:
    - PYTHON: "C:\\Python36_64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"

    - PYTHON: "C:\\Python37_64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"

install:
    # https://www.appveyor.com/docs/installed-software#python
    - if "%PYTHON_VERSION%" == "3.5" set "BASE_PYTHON_VERSION=36"
    - if "%PYTHON_VERSION%" == "3.6" set "BASE_PYTHON_VERSION=37"
    - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
    # These are already installed on appveyor.  Update them.
    - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
    - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
    - conda config --set always_yes yes
    - conda update -q conda
    - conda info
    - conda update -q --all
    - python -c "import sys; print(sys.version)"
    - python -c "import sys; print(sys.executable)"
    - python -c "import sys; print(sys.prefix)"
    - conda create --yes --name test_env python=%PYTHON_VERSION%
    - activate test_env
    - conda install -q  numpy scipy scikit-learn joblib pandas pytest
    - conda install -q -c msys2 m2w64-toolchain m2w64-dlfcn pywin32
    - pip install sklearn
    - set "CXX=gcc -pthread"
    - python setup.py build_ext --inplace --compiler=mingw32 -llibdl

test_script:
  - pytest
