build: false

image:
  - Visual Studio 2019

environment:
  matrix:
    - PYTHON_VERSION: 3.6
      MINICONDA: C:\Miniconda3-x64
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3-x64

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% numpy scipy scikit-learn joblib pandas pytest"
  - activate test-environment
  - pip install scikit-learn>=0.23.1
  - pip install setuptools>=24.0

test_script:
  - pytest
